Repository MicrosoftDocs/azure-docs.de-de, pull requests merged in 2019-04, with the labels that each got.

#274 Update container-registry-service-principal.md
  includes/container-registry-service-principal.md
Labels: Accepted, Technical Issue

#276 correct HRworks support email address
  articles/active-directory/saas-apps/hrworks-single-sign-on-tutorial.md
Labels: Accepted, Linguistic Suggestion

#284 Fix mistranslation
  articles/azure-monitor/platform/api-alerts.md
Labels: Accepted, In Progress

#283 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-sql-data-warehouse-connector.md
Labels: Accepted, In Progress

#281 Fix mistranslation
  articles/data-factory/connector-azure-sql-data-warehouse.md
Labels: Accepted, In Progress

#282 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-table-connector.md
Labels: Accepted, In Progress

#290 Fix mistranslation
  articles/data-factory/connector-azure-search.md
Labels: Accepted, In Progress, Linguistic Suggestion

#289 Fix mistranslation
  articles/azure-monitor/platform/archive-diagnostic-logs.md
Labels: Accepted, In Progress, Linguistic Suggestion

#288 Fix mistranslation
  articles/data-factory/connector-sql-server.md
Labels: Accepted, In Progress, Linguistic Suggestion

#287 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-sql-connector.md
Labels: Accepted, In Progress, Linguistic Suggestion

#291 Fix mistranslation
  articles/azure-monitor/insights/wire-data.md
Labels: Accepted, In Progress, Linguistic Suggestion

#292 Fix mistranslation
  articles/azure-monitor/platform/activity-logs-overview.md
Labels: Accepted, In Progress, Linguistic Suggestion

#293 Fix mistranslation
  articles/data-factory/connector-azure-sql-database-managed-insance.md
Labels: Accepted, In Progress, Linguistic Suggestion

#294 Fix mistranslation
  articles/data-factory/connector-azure-sql-database.md
Labels: Accepted, In Progress, Linguistic Suggestion

#296 Fix mistranslation
  articles/connectors/connectors-create-api-bingsearch.md
Labels: Accepted, In Progress

#295 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-automation.md
Labels: Accepted, In Progress

#298 Fix mistranslation
  articles/azure-maps/geofence-geojson.md
Labels: Accepted, In Progress

#297 Fix mistranslation
  articles/api-management/api-management-product-templates.md
Labels: Accepted, In Progress

#303 Fix mistranslation
  articles/automation/automation-manage-send-joblogs-log-analytics.md
Labels: Accepted, In Progress

#302 Fix mistranslation
  articles/automation/automation-solution-vm-management.md
Labels: Accepted, In Progress

#301 Fix mistranslation
  articles/azure-functions/functions-host-json.md
Labels: Accepted, In Progress

#300 Fix mistranslation
  articles/azure-functions/functions-host-json-v1.md
Labels: Accepted, In Progress

#306 Fix mistranslation
  articles/api-management/api-management-howto-use-azure-monitor.md
Labels: Accepted, In Progress

#305 Fix mistranslation
  articles/automation/automation-dsc-diagnostics.md
Labels: Accepted, In Progress

#311 Fix mistranslation
  articles/data-factory/connector-azure-table-storage.md
Labels: Accepted, In Progress

#310 Fix mistranslation
  articles/azure-monitor/insights/vminsights-log-search.md
Labels: Accepted, In Progress

#309 Fix mistranslation
  articles/data-factory/connector-web-table.md
Labels: Accepted, In Progress

#307 Fix mistranslation
  articles/api-management/api-management-error-handling-policies.md
Labels: Accepted, In Progress

#308 Fix mistranslation
  articles/api-management/api-management-howto-properties.md
Labels: Accepted, In Progress

#313 Fix mistranslation
  articles/azure-functions/functions-bindings-cosmosdb-v2.md
Labels: Accepted, In Progress

#312 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-search-connector.md
Labels: Accepted, In Progress
